[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/Y0lNxPSQb4NdUIoWfAHJ0", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/Y0lNxPSQb4NdUIoWfAHJ0" }
viaIR = true
optimizer = true
optimizer_runs = 1


remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@ccip/=lib/ccip/',
    '@chainlink-local/=lib/chainlink-local/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
